export default class StorageKeys {
  public static readonly AuthToken = 'AuthToken';
  public static readonly PathAds = 'PathAdsFromServer';
  public static readonly PathMarketing = 'PathMarketingFromServer';
  public static readonly PathSocial = 'PathSocialFromServer';
  public static readonly PathCallCenter = 'PathCallCenterFromServer';
  public static readonly PathProfiling = 'PathProfilingFromServer';
  public static readonly PathAudience = 'PathAudienceFromServer';
  public static readonly PathEMK = 'PathEMKFromServer';
  public static readonly PathNM = 'PathNMFromServer';
  public static readonly PathChattool = 'PathChattoolFromServer';
  public static readonly PathLoyalty = 'PathLoyaltyFromServer';
  public static readonly PathTicket = 'PathTicketFromServer';
  public static readonly PathCRM = 'PathCRMFromServer';
  public static readonly PathProductLibrary = 'PathProductLibraryFromServer';
  public static readonly PathSale = 'PathSaleFromServer';
  public static readonly PathEvent = 'PathEventFromServer';
  public static readonly UserInfo: 'UserInfo';
  public static readonly CacheListAllPageSocial = 'CacheListAllPageSocial';
  public static readonly CacheConfigsRelatedInfoSocial = 'CacheConfigsRelatedInfoSocial';
  public static readonly CacheListAccountActive = 'CacheListAccountActive';
  public static readonly CALL_CENTER_KEY_AGENT_EXTENSION = 'CALL_CENTER_KEY_AGENT_EXTENSION';
  public static readonly FIRE_BASE_TOKEN = 'FIRE_BASE_TOKEN';
  public static readonly KEY_CACHE_SETTING_ALL = 'KEY_CACHE_SETTING_ALL';
  public static readonly KEY_CACHE_SETTING = 'setting-account';
  public static readonly LOGIN_STATUS = 'LOGIN_STATUS';
  public static readonly SOCIAL_ROLES = 'SOCIAL_ROLES';
  public static readonly FINGER_STATUS = 'FINGER_STATUS';
  public static readonly USER_NAME = 'USER_NAME';
  public static readonly PASSWORD = 'PASSWORD';
}