export default class EmitKeys {
	/* CALL CENTER KEYS */
	public static readonly CALL_CENTER_DID_CONNECTED = 'CALL_CENTER_DID_CONNECTED';
	public static readonly CALL_CENTER_DID_DIS_CONNECTED = 'CALL_CENTER_DID_DIS_CONNECTED';
	public static readonly CALL_CENTER_MAKE_CALL = 'CALL_CENTER_MAKE_CALL';
	public static readonly CALL_CENTER_INCOMING_CALL = 'CALL_CENTER_INCOMING_CALL';
	public static readonly CALL_CENTER_DID_CHANGE_SIGNAL_STATE = 'CALL_CENTER_DID_CHANGE_SIGNAL_STATE';
	public static readonly CALL_CENTER_DO_HANG_UP = 'CALL_CENTER_DO_HANG_UP';
	public static readonly CALL_CENTER_END_CALL = 'CALL_CENTER_END_CALL';
	public static readonly CALL_CENTER_DID_END_CALL = 'CALL_CENTER_DID_END_CALL';
	public static readonly CALL_CENTER_SPEAKER_CHANGE = 'CALL_CENTER_SPEAKER_CHANGE';
	public static readonly CALL_CENTER_DID_SPEAKER_CHANGE = 'CALL_CENTER_DID_SPEAKER_CHANGE';
	public static readonly CALL_CENTER_ANSWER_PHONE = 'CALL_CENTER_ANSWER_PHONE';
	public static readonly CALL_CENTER_DID_ANSWER_PHONE = 'CALL_CENTER_DID_ANSWER_PHONE';
	public static readonly CALL_CENTER_CONNECT_SUCCESS = 'CALL_CENTER_CONNECT_SUCCESS';
	public static readonly CALL_CENTER_STATUS_CHANGE = 'CALL_CENTER_STATUS_CHANGE';
	public static readonly CALL_CENTER_REJECT_PHONE = 'CALL_CENTER_REJECT_PHONE';
	public static readonly CALL_CENTER_DID_REJECT_PHONE = 'CALL_CENTER_DID_REJECT_PHONE';
	public static readonly CALL_CENTER_SEND_DIGIT = 'CALL_CENTER_SEND_DIGIT';
	public static readonly CALL_CENTER_HANDLE_ANOTHER_DEVICE = 'CALL_CENTER_HANDLE_ANOTHER_DEVICE';

	/* ****** */
	public static readonly PUSH_TOKEN_UPDATED = 'PUSH_TOKEN_UPDATED';
}