
import LocalizedStrings from 'react-native-localization';

export default new LocalizedStrings({
  vi: {
    Home: 'Trang chủ',
    Order: 'Đặt hàng',
    password: 'Mật khẩu',
    signup: 'Đăng ký',
    Shipment_Details:'Thông tin giao hàng',
    signupAccount: 'Đăng ký tài khoản',
    seeAll: 'Tất cả',
    UserInputPhone: 'Nhập số điện thoại',
    ForgetPassword:'Quên số mật khẩu ?',
    LoginBy: 'Đăng nhập bằng',
    PhoneEmpty:'Vui lòng nhập số điện thoại',
    PassEmpty:'Vui lòng nhập mật khẩu',
    LoginIncorrect:'Mật khẩu hoặc số điện thoại không chính xác.',
    PhoneNumber:'Số điện thoại',
    CancelRegister:'Hủy đăng ký',
    CancelUpdate:'Hủy cập nhật',
    NewPassPlh:'Mật khẩu mới',
    Continue:'Tiếp tục',
    ResendPassRemaining:'Gửi lại mật khẩu sau {time}/60s',
    ResendCodeRemaining:'Gửi lại mã sau {time}/60s',
    ResendPass:'Gửi lại mật khẩu',
    RegisterNote:'Bằng cách đăng ký tài khoản, bạn xác nhận đã đọc và đồng ý với các',
    RegisterNoteLast:'của Sakuko',
    TermCondition:'Điều kiện - Điều khoản Chương trình Khách hàng Thân thiết',
    SendPassSMSSuccessful:'Mật khẩu mới đã được gửi qua SMS đến số điện thoại {phone}',
    SendPassSMSSuccessfulEmail:'Mã xác thực đã được gửi đến e-mail {email}',
    RegisterCancel:'Bạn có chắc chắn muốn huỷ đăng ký số điện thoại này ?',
    UpdateSuccessfulEmail:'Cập nhật E-mail thành công',
    UpdateSuccessfulPhone:'Cập nhật số điện thoại thành công',
    RegisterCancelEmail:'Bạn có chắc chắn muốn huỷ đăng ký email này ?',
    Agree:'Đồng ý',
    Cancel:'Hủy bỏ',
    ResetPassowrd:'Tìm lại mật khẩu',
    ScanQR:'Quét mã',
    MyVoucher:'Voucher của tôi',
    Like:'Yêu thích',
    News:'Tin tức',
    Voucher:'Voucher',
    Product:'Sản phẩm',
    SakukoTV:'Sakuko TV',
    VoucherExpired:'Đã hết thời gian áp dụng',
    VoucherNotYetTime:'Chưa đến thời gian áp dụng',
    VoucherValid:'Đang trong thời gian áp dụng',
    view:'Lượt xem',
    Card:'Dùng thẻ',
    Map:'Địa điểm',
    Account:'Tài khoản',
    Notification:'Thông báo',
    Point:'điểm',
    When:'Lúc',
    ReadAll:'Đã đọc tất cả',
    RemoveAll:'Xoá tất cả',
    Remove:'Xoá',
    MapDirection:'Chỉ đường đến đây',
    StoreDetail:'Chi tiết cửa hàng',
    StoreName:'Tên cửa hàng',
    Hotline:'Hotline',
    Email: 'E-mail',
    Region:'Tỉnh thành',
    Address:'Địa chỉ',
    FindDirection:'Tìm đường',
    SelectionRegion:'Chọn thành phố hoặc tỉnh thành',
    All: 'Tất cả',
    MySelf: 'Của tôi',
    Filter1: 'Bộ lọc',
    FindVoucher:'Nhập tên vouch ...',
    Restore:'Khôi phục',
    Apply:'Áp dụng',
    VoucherStatus:'Trạng thái voucher',
    Active:'Đang hoạt động',
    Expired:'Đã hết hạn',
    Used:'Đã sử dụng',
    Lastest:'Mới nhất',
    Popular:'Phổ biến',
    PointDownUp:'Điểm từ thấp đến cao',
    PointUpDown:'Điểm từ cao đến thấp',
    Arrange:'Sắp xếp',
    Category:'Danh mục',
    Filter:'Lọc',
    DistancePoint:'Khoảng điểm',
    VoucherPointCond:'Hiển thị những voucher đủ điểm',
    Rate:'Đánh giá',
    VoucherNumberRemain:'Số lượng voucher còn lại',
    ProgInfo: 'Thông tin chương trình',
    ViewMore:'Xem thêm',
    Palace:'Địa điểm áp dụng',
    Call:'Gọi điện',
    Feedback:'Thông tin phản hồi',
    Reply: 'Trả lời',
    Share:'Chia sẻ',
    ViewAllFeedback:'Xem thêm {num} phản hồi',
    Comment:'Chia sẻ suy nghĩ về voucher',
    ChangePointVoucher:'Đổi điểm lấy voucher',
    VoucherExpiredTime:'Bạn có thể lấy thêm voucher này sau {num}',
    RateVoucher:'Hãy cho chúng tôi biết đánh giá của bạn về voucher này.',
    RatingOk:'Cảm ơn bạn đã dành thời gian đánh giá voucher.',
    RateProd:'Hãy cho chúng tôi biết đánh giá của bạn về sản phẩm này.',
    RatingProdOk:'Cảm ơn bạn đã dành thời gian đánh giá sản phẩm.',
    Close:'Đóng',
    Order1:'Đặt hàng',
    AddToCart:'Thêm vào giỏ hàng',
    ProdInfo:'Thông tin sản phẩm',
    ContinueShopping:'Tiếp tục mua sắm',
    Cart:'Giỏ hàng',
    Price:'Giá',
    MyOrder: 'Đơn hàng',
    Contact: 'Liên hệ với Venesa',
    Confirm: 'Xác nhận',
    TotalOrder :'Tổng hoá đơn',
    FullName :'Họ và tên',
    FullNamePlh:'Nhập họ tên',
    AddressPlh: 'Nhập địa chỉ',
    EmailPlh:'Nhập email',
    FullNameEmpty:'Họ và tên không được phép để trống',
    AddressEmpty:'Địa chỉ không được phép để trống',
    EmailInvalid:'Email không hợp lệ',
    EmailEmpty:'Email không được để trống',
    PhoneNumberValid:'Số điện thoại không hợp lệ',
    PhoneNumberEmpty:'Số điện thoại không được phép để trống',
    PasswordEmpty:'Vui lòng nhập mật khẩu',
    PasswordOldEmpty:'Vui lòng nhập mật khẩu cũ',
    PasswordNewEmpty:'Vui lòng nhập mật khẩu mới',
    RePasswordEmpty:'Vui lòng nhập mật khẩu nhập lại',
    RePasswordNewEmpty:'Vui lòng nhập lại mật khẩu mới.',
    PasswordNewMinLimit:'Mật khẩu mới phải có tối thiểu 6 ký tự',
    PasswordNewMaxLimit:'Mật khẩu mới không được quá 20 ký tự',
    RePasswordInvalid:'Mật khẩu nhập lại không trùng mật khẩu mới',
    Note:'Ghi chú',
    NotePlh:'Nhập ghi chú',
    Update:'Cập nhật',
    LoginUserPassInvalid:'Số điện thoại hoặc mật khẩu không chính xác. Vui lòng kiểm tra lại.',
    UserProfile:'Thông tin cá nhân',
    Or: 'Hoặc',
    ForgotPassword: 'Quên mật khẩu ?',
    DontHaveAccount: 'Bạn chưa có tài khoản ?',
    Login:'Đăng nhập',

    RewardPoint:'Điểm thưởng',
    UnusedVoucher: 'Voucher chưa dùng',
    MyOrders:'Đơn hàng của tôi',
    HistoryTransaction: 'Lịch sử giao dịch',
    Setting : 'Cài đặt',
    Terms:'Điều khoản và điều kiện',
    AppInfo:'Thông tin về ứng dụng',
    Logout:'Đăng xuất',

    ProcessError:'Có lỗi xảy ra trong quá trình xử lý.',
    LoginPassInvalid :'Mật khẩu sai. Hệ thống đã gửi tin nhắn chứa mật khẩu đã được gửi quý khách.',
    RegisterExist : 'SĐT đã được sử dụng để đăng ký tài khoản khác, vui lòng đăng nhập hoặc sử dụng sđt khác để đăng ký',
    EmailExist : 'Email đã được sử dụng, vui lòng sử dụng Email khác để cập nhật',

    InformationUpdate: 'Cập nhật thông tin',
    OrderOfUser: 'Đơn hàng của tôi',
    Information: 'Thông tin chung',
    ChangeAvatar: 'Thay đổi ảnh đại diện',
    Birthday: 'Ngày/tháng/năm sinh',
    Sex: 'Giới tính',
    InformationContact: 'Thông tin liên lạc',

    noConnection : 'Không có kết nối internet. Vui lòng kiểm tra lại.',
    InternetReconnect :'Internet đã kết nối lại',
    updatePhoneUser : 'Bằng việc thay đổi số điện thoại bạn xác nhận đồng ý thay đổi số điện thoại và mật khẩu đăng nhập vào ứng dụng Sakuko Loyalty.',

    SelectCity: 'Chọn tỉnh thành',

    NotFoundVoucher:'Không có voucher nào trong danh sách',
    Discount : 'Giảm',
    ExchangePointConfirm: 'Đồng ý đổi điểm',

    mount: 'VNĐ',
    Status: 'Trạng thái',
    ProductCount: 'Số lượng sản phẩm',
    OrderTime : 'Thời gian tạo đơn',
    WAIT : 'Chờ xử lý',
    RECEIVED: 'Đã tiếp nhận',
    DELIVER: 'Đang giao hàng',
    ACCOMPLISHED: 'Hoàn tất',
    CANCEL: 'Hủy bỏ',
    DislayDay : 'Thứ',
    Sunday: 'Chủ nhật',
    StatusOrder: 'Trạng thái đơn hàng',
    Count: 'Số lượng',
    ApplyNotification: 'Nhận thông báo từ Venesa',
    Language: 'Ngôn ngữ',
    Vietnamese : 'Tiếng Việt',
    HotlineCSKH : 'Hotline CSKH',
    face : 'Facebook',
    AppInfoTitle : 'SAKUKO - Tích điểm thông minh, nhận quà hấp dẫn',
    AppVersion: 'Phiên bản 1.0',
    AppProducion : 'Giới thiệu về app',

    VoucherCode: 'Mã Voucher',
    ValidUntil:'Có hiệu lực đến :',
    MyVoucherNumber:'Bạn đang có {number} mã của voucher này',
    ExpiredTime:'Đã hết hiệu lực',

    LocationDenied:'Quyền truy cập vị trí đã bị người dùng từ chối.',
    DistanceStore:'Cách {number}km',
    StoreVoucherApply:'Đang có {number} cửa hàng áp dụng Voucher này',
    VoucherStores:'Danh sách cửa hàng',
    ViewMoreAnswer:'Xem thêm {number} trả lời',
    CommentTitle:'Bình luận',
    DevelopBy: 'Được phát triển bởi',
    TermAndCondition: 'Điều kiện & điều khoản',
    TermAndConditionUser : 'Điều kiện - Điều khoản Chương trình Khách hàng Thân thiết',
    ChangePassword : 'Thay đổi mật khẩu',
    Change: 'Thay đổi',
    English: 'Tiếng Anh',
    PasswordOldPlc: 'Mật khẩu cũ',
    PasswordNewPlc: 'Mật khẩu mới',
    PasswordConfirmPlc: 'Nhập lại mật khẩu mới',
    NoProductInCart:'Không có sản phẩm nào trong giỏ hàng',
    Male: 'Nam',
    Female: 'Nữ',
    ChangePassValid: 'Yêu cầu mật khẩu phải có độ dài từ 6 - 20 ký tự',
    UpdatePhone: 'Cập nhật số điện thoại',
    UpdateEmail: 'Cập nhật E-mail',
    TotalPrice:'Tổng đơn hàng',
    NoNote:'Không có ghi chú',
    OrderConfirm :'Xác nhận đặt hàng',
    OrderCompletedNoti:'Đơn đặt hàng đã được gửi. Nhân viên tiếp nhận của Sakuko sẽ liên hệ lại tới quý khách.',
    NoneComments:'Hiện chưa có bình luận nào',
    TopProdSell:'Top sản phẩm bán chạy',
    NewProdArrival:'Sản phẩm mới về',
    ProdCommingSoon:'Sản phẩm sắp ra mắt',
    ProdOrder:'Sản phẩm order',
    NoneNews:'Không có tin tức nào được hiển thị vào lúc này',
    NoneVouchers:'Không có voucher nào được hiển thị vào lúc này',
    NoneVideos:'Không có video nào được hiển thị vào lúc này',
    NoOrder:'Không có đơn hàng',
    NoHistory:'Không có lịch sử giao dịch',
    LoginSuccess: 'Đăng nhập thành công vào hệ thống.',
    LoginFail:  'Tài khoản không hợp lệ.',
    NoneVoucherWishList : 'Chưa có voucher nào trong danh sách yêu thích của bạn',
    NoneProdWishList : 'Chưa có sản phẩm nào trong danh sách yêu thích của bạn',
    SearchHolderMyVoucher:'Tìm kiếm voucher ...',
    SearchHolderVoucher:'Tìm kiếm voucher ...',
    SearchHolderProduct:'Tìm kiếm ...',
    PhoneErrorValid: 'Số điện thoại không hợp lệ.',
    EmailErrorValid: 'E-mail không đúng định dạng.',
    GenderDefault: 'Chưa xác định',
    ApplicationDev: 'Ứng dụng di động Sakuko được phát triển bởi Mobio',
    NoVoucherComment:'Hiện voucher chưa có bình luận nào',
    TimeAgo:'{time} trước',
    Bought:'Đã mua',
    ValidVouchers:'Bạn có {num} mã voucher còn hiệu lực',
    NoneValidVouchers:'Bạn đã sử dụng hết mã voucher',
    NoneProduct:'Chưa có sản phẩm nào',
    NoneListNews:'Chưa có tin tức nào',
    Timeout:'Xử lý quá thời hạn cho phép',
    Exit:'Thoát',
    Select:'Chọn',
    Undefined:'Chưa có thông tin',
    GenderSelect: 'Chọn giới tính',
    emptyBirthdayMessage:'Ngày sinh không được phép để trống',
    VerifyPhone:'Xác thực số điện thoại',
    ChangePasswordSuccessful:'Đổi mật khẩu thành công',
    PasswordOldInvalid:'Mật khẩu cũ không chính xác. Vui lòng kiểm tra lại.',
    OrderCancel:'Đã huỷ',
    OrderCompleted:'Hoàn thành',
    OrderDeliver:'Đang giao',
    OrderReceived:'Đã tiếp nhận',
    OrderWait:'Chờ xử lý',
    RegisterAppError:'Có lỗi xảy ra. Đăng ký phần mềm không thành công',
    VideoError: 'Đã có lỗi xảy ra với video này',
    NotFound:'Không có kết quả phù hợp với nội dung tìm kiếm.',
    NotNotificationItem:'Bạn không có thông báo nào',
    NotData:'Không có dữ liệu',
    NotTransaction:'Bạn chưa có giao dịch nào',
    RegisterAppSuccess:'Cập nhật thông tin thiết bị thành công.',
    FreeVoucher:'Lấy voucher miễn phí',
    Free:'Miễn phí',
    VoucherNotStart:'Chương trình chưa bắt đầu',
    VoucherLimitPerProfile:'Bạn đã lấy tối đa {num} mã của voucher này.',
    VoucherRemainingPerProfile:'Bạn chỉ có thể lấy được thêm {num} voucher.',
    VoucherNotNextGet:'Bạn có thể lấy thêm voucher này sau {num}',
    Unlimited:'Không giới hạn',
    VoucherUnEnoughPoint:'Bạn không đủ điểm để đổi voucher',
    VoucherOrderFrom:'Voucher này được tặng khi mua hàng với giá trị hoá đơn từ {from} trở lên',
    VoucherOrderFromTo:'Voucher này được tặng khi mua hàng với giá trị hoá đơn từ {from} đến {to}',
    VoucherOrderTo:'Voucher này được tặng khi mua hàng với giá trị hoá đơn đến {to}',
    CameraRoll: 'Camera Roll',
    ImagePicker:'Chọn ảnh',
    SendImages :'Gửi {num} ảnh',
    GivePoints : 'Bạn được tặng điểm',
    ExpiredPoint : 'Bạn bị trừ điểm do hết hạn',
    UseVoucher: 'Bạn đã sử dụng voucher',
    RedeemPoints : 'Bạn đã đổi điểm lấy voucher',
    DonateVoucher:'Bạn đã được tặng voucher',
    Reason:'Lý do : ',
    Store:'Cửa hàng',
    StoreRate:'Bấm vào đây để đánh giá chất lượng dịch vụ tại cửa hàng',
    StoreRatePopup:'Bạn vui lòng đánh giá chất lượng giao dịch tại cửa hàng',
    RatedTransaction:'Bạn đã đánh giá giao dịch này.',
    RateTransaction:'Đánh giá dịch vụ',
    RateTransactionTitle: 'Bạn có thể cho chúng tôi biết thêm được không ?',
    RateReasonLabel:'Lý do đánh giá thấp',
    RateReasonSelect:'Chọn lý do đánh giá thấp',
    Optional:'Không bắt buộc',
    NotePlh1:'Viết ghi chú...',
    SendEvaluate:'Gửi đánh giá',
    SearchProvinces:'Tìm kiếm tỉnh thành ...',
    TransactionReasonRequire:'Bạn vui lòng chọn lý do đánh giá thấp.',
    RemaindMeLater:'Nhắc tôi sau',
    UpdateMessage:'Ứng dụng đã có phiên bản mới. Bạn có muốn cập nhật ngay không ?',
    EmailNotEmpty:'Email không được phép để trống',
    SearchNotProvinces:'Không có kết quả phù hợp.',
    Compact:'Rút gọn',
    PhoneExist : 'Số điện thoại đã được sử dụng, vui lòng sử dụng số điện thoại khác để cập nhật',
    TimeUp: 'Mã voucher đã hết thời gian sử dụng.',
    LimitChars:'{num}/{num1} ký tự',
    VoucherLimitPerDay:'Bạn không thể lấy được mã voucher do hết số lượng mã voucher phát hành trong 1 ngày.',
    VoucherLimitTotal:'Bạn không thể lấy được mã voucher do hết số lượng mã voucher toàn chương trình.',
    ScanStoreCodeFail: 'Quét mã không thành công. Bạn vui lòng quét lại mã hoặc chắc chắn đây là mã của cửa hàng.',
    ScanStoreCodeSuccess: 'Quét mã thành công.',
    GitPointShopping:'Bạn được tặng điểm khi mua sắm tại của hàng',
    UpdateAvatarNotName:'Bạn vui lòng cập nhật tên trước khi cập nhật ảnh đại diện',
    PasswordHasBeenChanged:'Mật khẩu đã được thay đổi ở thiết bị khác',
    ChooseReason:'Vui lòng chọn lý do đáng giá.',
    NotApplyNotification: 'Không nhận thông báo từ Venesa',
    Developers:'Tìm hiểu thêm về nhà phát triển',
    InvalidBarcode:'Mã thẻ không hợp lệ',
    BackExist:'Ấn thêm lần nữa để thoát ứng dụng',

    // new
    ViewAllVoucher: 'Bạn đã xem hết toàn bộ voucher hiện có',
    ViewAllBlog: 'Bạn đã xem hết toàn bộ blog hiện có',
    ViewAllProd: 'Bạn đã xem hết toàn bộ sản phẩm hiện có',
    ViewAllService: 'Bạn đã xem hết toàn bộ dịch vụ hiện có',

    RateService:'Hãy cho chúng tôi biết đánh giá của bạn về dịch vụ này.',
    RateServiceOk:'Cảm ơn bạn đã dành thời gian đánh giá dịch vụ.',
    ManipulationSuccess:'Thao tác thành công.',
    ManipulationUnSuccess:'Thao tác không thành công.'
,
  },
});
